# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='domainData',
            fields=[
                ('tableId', models.AutoField(primary_key=True, serialize=False)),
                ('cReqId', models.CharField(max_length=255)),
                ('domainName', models.CharField(max_length=512, unique=True)),
                ('data', models.TextField(default='')),
                ('domainStructureQueueId', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='domainDataMeta',
            fields=[
                ('tableId', models.AutoField(primary_key=True, serialize=False)),
                ('domainStructureQueueId', models.IntegerField()),
                ('key', models.TextField(default='')),
                ('value', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='pageData',
            fields=[
                ('tableId', models.AutoField(primary_key=True, serialize=False)),
                ('domainId', models.CharField(default='', max_length=512)),
                ('pageUrl', models.CharField(max_length=255)),
                ('data', models.TextField(default='')),
                ('title', models.TextField(default='')),
                ('images', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('keywords', models.TextField(default='')),
                ('sReqId', models.CharField(max_length=255)),
            ],
        ),
    ]
