# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-24 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='second',
            fields=[
                ('reqId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('domainName', models.CharField(default='', max_length=512)),
                ('data', models.TextField(default='')),
                ('header', models.TextField(default='')),
            ],
        ),
    ]
